// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: season.proto

#ifndef PROTOBUF_season_2eproto__INCLUDED
#define PROTOBUF_season_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace season {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_season_2eproto();
void protobuf_AssignDesc_season_2eproto();
void protobuf_ShutdownFile_season_2eproto();

class key;
class data;

// ===================================================================

class key : public ::google::protobuf::Message {
 public:
  key();
  virtual ~key();
  
  key(const key& from);
  
  inline key& operator=(const key& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const key& default_instance();
  
  void Swap(key* other);
  
  // implements Message ----------------------------------------------
  
  key* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const key& from);
  void MergeFrom(const key& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string season = 1;
  inline bool has_season() const;
  inline void clear_season();
  static const int kSeasonFieldNumber = 1;
  inline const ::std::string& season() const;
  inline void set_season(const ::std::string& value);
  inline void set_season(const char* value);
  inline void set_season(const char* value, size_t size);
  inline ::std::string* mutable_season();
  inline ::std::string* release_season();
  
  // @@protoc_insertion_point(class_scope:season.key)
 private:
  inline void set_has_season();
  inline void clear_has_season();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* season_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_season_2eproto();
  friend void protobuf_AssignDesc_season_2eproto();
  friend void protobuf_ShutdownFile_season_2eproto();
  
  void InitAsDefaultInstance();
  static key* default_instance_;
};
// -------------------------------------------------------------------

class data : public ::google::protobuf::Message {
 public:
  data();
  virtual ~data();
  
  data(const data& from);
  
  inline data& operator=(const data& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const data& default_instance();
  
  void Swap(data* other);
  
  // implements Message ----------------------------------------------
  
  data* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const data& from);
  void MergeFrom(const data& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:season.data)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_season_2eproto();
  friend void protobuf_AssignDesc_season_2eproto();
  friend void protobuf_ShutdownFile_season_2eproto();
  
  void InitAsDefaultInstance();
  static data* default_instance_;
};
// ===================================================================


// ===================================================================

// key

// required string season = 1;
inline bool key::has_season() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void key::set_has_season() {
  _has_bits_[0] |= 0x00000001u;
}
inline void key::clear_has_season() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void key::clear_season() {
  if (season_ != &::google::protobuf::internal::kEmptyString) {
    season_->clear();
  }
  clear_has_season();
}
inline const ::std::string& key::season() const {
  return *season_;
}
inline void key::set_season(const ::std::string& value) {
  set_has_season();
  if (season_ == &::google::protobuf::internal::kEmptyString) {
    season_ = new ::std::string;
  }
  season_->assign(value);
}
inline void key::set_season(const char* value) {
  set_has_season();
  if (season_ == &::google::protobuf::internal::kEmptyString) {
    season_ = new ::std::string;
  }
  season_->assign(value);
}
inline void key::set_season(const char* value, size_t size) {
  set_has_season();
  if (season_ == &::google::protobuf::internal::kEmptyString) {
    season_ = new ::std::string;
  }
  season_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* key::mutable_season() {
  set_has_season();
  if (season_ == &::google::protobuf::internal::kEmptyString) {
    season_ = new ::std::string;
  }
  return season_;
}
inline ::std::string* key::release_season() {
  clear_has_season();
  if (season_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = season_;
    season_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// data


// @@protoc_insertion_point(namespace_scope)

}  // namespace season

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_season_2eproto__INCLUDED
